name: 'Incentive services setup'
description: 'Checks out the needed repos and sets the java version'

runs:
    using: "composite"
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Checkout math
        uses: actions/checkout@v2
        with:
          repository: upbcuk/upb.crypto.math
          path: ../upb.crypto.math
          ref: master
      - name: Checkout craco
        uses: actions/checkout@v2
        with:
          repository: upbcuk/upb.crypto.craco
          path: ../upb.crypto.craco
          ref: protocolupdates
      - uses: actions/setup-java@v1
        with:
          java-version: '15.0.1' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
