language: java
jdk:
  - openjdk15

before_install:
  - pushd ..
  - git clone https://github.com/upbcuk/upb.crypto.craco.git
  - pushd upb.crypto.craco
  - git checkout protocolupdates
  - git pull
  - popd
  - git clone https://github.com/upbcuk/upb.crypto.math.git
  - popd

services: docker

deploy:
  provider: script
  script: bash .travis/docker_release.sh
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v.*$"
