language: java
jdk:
  - openjdk15

before_install: ls -la
after_install: ls -la

services: docker

deploy:
  provider: script
  script: bash .travis/docker_release.sh
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v.*$"
