sudo: false
language: java
jdk:
  - openjdk15

services: docker

deploy:
  provider: script
  script: bash .travis/docker_release
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v(\d+\.)?(\d+\.)?(\*|\d+)$"