version: '3.5'

services:
  infoservice:
    image: cryptimeleon/incentive-service-info:0.5.0
    ports:
      - "8000:8000"
    networks:
      - provider
    hostname: infoservice
  incentiveservice:
    image: cryptimeleon/incentive-service-incentive:0.5.0
    ports:
      - "8012:8012"
    environment:
      - INFO_SERVICE_URL=http://infoservice:8000/
      - BASKET_SERVICE_URL=http://basketservice:8010/
      - DSPROTECTION_SERVICE_URL=http://dsprotectionservice:8004/
    networks:
      - provider
    hostname: incentiveservice
  basketservice:
    image: cryptimeleon/incentive-service-basket:0.5.0
    ports:
      - "8010:8010"
    networks:
      - provider
    hostname: basketservice
  dsprotectionservice:
    image: cryptimeleon/incentive-service-dsprotection:0.5.0
    ports:
      - "8004:8004"
    environment:
      - INFO_SERVICE_URL=http://infoservice:8000/
    networks:
      - provider
    hostname: dsprotectionservice
  bootstrapservice:
    image: cryptimeleon/incentive-service-bootstrap:0.5.0
    environment:
      - BASKET_SERVICE_URL=http://basketservice:8010/
      - INCENTIVE_SERVICE_URL=http://incentiveservice:8012/
    networks:
      - provider
  web:
    image: cryptimeleon/incentive-system-web:0.5.0
    ports:
    - "8080:80"
networks:
  provider:
    driver: bridge
    ipam:
      driver: default
