version: '3.5'

services:
  issueservice:
    image: cryptimeleon/incentive-service-issue:0.4.0
    ports:
      - "8001:8001"
    environment:
      - INFO_SERVICE_URL=http://infoservice:8004/
    networks:
      - provider
    hostname: issueservice
  creditservice:
    image: cryptimeleon/incentive-service-credit:0.4.0
    ports:
      - "8002:8002"
    environment:
      - INFO_SERVICE_URL=http://infoservice:8004/
      - BASKET_SERVICE_URL=http://basketservice:8003/
    networks:
      - provider
    hostname: creditservice
  basketservice:
    image: cryptimeleon/incentive-service-basket:0.4.0
    ports:
      - "8003:8003"
    networks:
      - provider
    hostname: basketservice
  infoservice:
    image: cryptimeleon/incentive-service-info:0.4.0
    ports:
      - "8004:8004"
    networks:
      - provider
    hostname: infoservice

networks:
  provider:
    driver: bridge
    ipam:
      driver: default

