services:
  reverse-proxy:
    image: traefik:v2.9
    command: --providers.docker
    ports:
      - "8009:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - provider
  infoservice:
    image: cptml/incsys-info:latest
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_SERVLET_CONTEXT_PATH=/info
      - PROVIDER_SHARED_SECRET=${PROVIDER_SHARED_SECRET}
      - STORE_SHARED_SECRET=${STORE_SHARED_SECRET}
      - SPRINGFOX_HOST=${HOST:-incentives.cs.uni-paderborn.de}
    labels:
      - traefik.http.routers.info.rule=PathPrefix(`/info`)
      - traefik.http.services.info.loadbalancer.server.port=8000
    networks:
      - provider
    hostname: infoservice
  incentiveservice:
    image: cptml/incsys-provider:latest
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_SERVLET_CONTEXT_PATH=/incentive
      - PROVIDER_SHARED_SECRET=${PROVIDER_SHARED_SECRET}
      - INCENTIVE_SERVICE_PROVIDER_SECRET=${INCENTIVE_PROVIDER_SECRET}
      - INFO_SERVICE_URL=http://infoservice:8000/info
      - SPRINGFOX_HOST=${HOST:-incentives.cs.uni-paderborn.de}
    labels:
      - traefik.http.routers.incentive.rule=PathPrefix(`/incentive`)
      - traefik.http.services.incentive.loadbalancer.server.port=8012
    networks:
      - provider
    hostname: incentiveservice
  basketservice:
    image: cptml/incsys-store:latest
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_SERVLET_CONTEXT_PATH=/basket
      - STORE_NAME=First Store
      - BASKET_SERVICE_PROVIDER_SECRET=${BASKET_PROVIDER_SECRET}
      - STORE_SHARED_SECRET=${STORE_SHARED_SECRET}
      - INFO_SERVICE_URL=http://infoservice:8000/info
      - INCENTIVE_SERVICE_URL=http://incentiveservice:8012/incentive
      - SPRINGFOX_HOST=${HOST:-incentives.cs.uni-paderborn.de}
    labels:
      - traefik.http.routers.basket.rule=PathPrefix(`/basket`)
      - traefik.http.services.basket.loadbalancer.server.port=8010
    networks:
      - provider
    hostname: basketservice
  basketservice-two:
    image: cptml/incsys-store:latest
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_SERVLET_CONTEXT_PATH=/basket-two
      - STORE_NAME=Second Store
      - BASKET_SERVICE_PROVIDER_SECRET=${BASKET_PROVIDER_SECRET_TWO}
      - STORE_SHARED_SECRET=${STORE_SHARED_SECRET}
      - INFO_SERVICE_URL=http://infoservice:8000/info
      - INCENTIVE_SERVICE_URL=http://incentiveservice:8012/incentive
      - SPRINGFOX_HOST=${HOST:-incentives.cs.uni-paderborn.de}
    labels:
      - traefik.http.routers.basket-two.rule=PathPrefix(`/basket-two`)
      - traefik.http.services.basket-two.loadbalancer.server.port=8010
    networks:
      - provider
    hostname: basketservicetwo
  bootstrapservice:
    image: cptml/incsys-bootstrap:latest
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - BASKET_SERVICE_URLS=http://basketservice:8010/basket,http://basketservicetwo:8010/basket-two
      - BASKET_SERVICE_PROVIDER_SECRETS=${BASKET_PROVIDER_SECRET},${BASKET_PROVIDER_SECRET_TWO}
      - INCENTIVE_SERVICE_URL=http://incentiveservice:8012/incentive
      - INCENTIVE_SERVICE_PROVIDER_SECRET=${INCENTIVE_PROVIDER_SECRET}
    depends_on:
      - basketservice
      - basketservice-two
      - incentiveservice
    networks:
      - provider
  web:
    image: cptml/incsys-web:latest
    ports:
      - "8001:80" # Need 8080 and 80 for traefik
    labels:
      - traefik.http.routers.web.rule=PathPrefix(`/`)
      - traefik.http.services.web.loadbalancer.server.port=80
    networks:
      - provider
  watchtower:
    image: containrrr/watchtower
    ports:
      - "8002:8080" # Need 8080 and 80 for traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    environment:
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
networks:
  provider:
    driver: bridge
    ipam:
      driver: default

