services:
  infoservice:
    image: cryptimeleon/incentive-service-info:0.5.0
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - PROVIDER_SHARED_SECRET=${SHARED_SECRET}
      - SERVER_SERVLET_CONTEXT_PATH=${INFO_CONTEXT:-/info}
      - SPRINGFOX_HOST=${HOST:-incentives.cs.uni-paderborn.de}
    networks:
      - provider
    hostname: infoservice
  incentiveservice:
    image: cryptimeleon/incentive-service-incentive:0.5.0
    ports:
      - "8012:8012"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - PROVIDER_SHARED_SECRET=${SHARED_SECRET}
      - BASKET_SERVICE_REDEEM_SECRET=${BASKET_REDEEM_SECRET}
      - INCENTIVE_SERVICE_PROVIDER_SECRET=${INCENTIVE_PROVIDER_SECRET}
      - SERVER_SERVLET_CONTEXT_PATH=${INCENTIVE_CONTEXT:-/incentive}
      - SPRINGFOX_HOST=${HOST:-incentives.cs.uni-paderborn.de}
    networks:
      - provider
    hostname: incentiveservice
  basketservice:
    image: cryptimeleon/incentive-service-basket:0.5.0
    ports:
      - "8010:8010"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - BASKET_SERVICE_REDEEM_SECRET=${BASKET_REDEEM_SECRET}
      - BASKET_SERVICE_PAY_SECRET=${BASKET_PAY_SECRET}
      - BASKET_SERVICE_PROVIDER_SECRET=${BASKET_PROVIDER_SECRET}
      - SERVER_SERVLET_CONTEXT_PATH=${BASKET_CONTEXT:-/basket}
      - SPRINGFOX_HOST=${HOST:-incentives.cs.uni-paderborn.de}
    networks:
      - provider
    hostname: basketservice
  dsprotectionservice:
    image: cryptimeleon/incentive-service-dsprotection:0.5.0
    ports:
      - "8004:8004"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - JAVA_TOOL_OPTIONS=-Xms512m -Xmx2048m
      - SERVER_SERVLET_CONTEXT_PATH=${DSPROTECTION_CONTEXT:-/dsprotection}
      - SPRINGFOX_HOST=${HOST:-incentives.cs.uni-paderborn.de}
    networks:
      - provider
    hostname: dsprotectionservice
  bootstrapservice:
    image: cryptimeleon/incentive-service-bootstrap:0.5.0
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - BASKET_SERVICE_PROVIDER_SECRET=${BASKET_PROVIDER_SECRET}
      - INCENTIVE_SERVICE_PROVIDER_SECRET=${INCENTIVE_PROVIDER_SECRET}
    depends_on:
      - basketservice
      - incentiveservice
    networks:
      - provider
  web:
    image: cryptimeleon/incentive-system-web:0.5.0
    ports:
      - "8080:80"
networks:
  provider:
    driver: bridge
    ipam:
      driver: default

