version: '3.5'

services:
  infoservice:
    image: cptml/incsys-info:latest
    ports:
      - "8000:8000"
    networks:
      - provider
    hostname: infoservice
  incentiveservice:
    image: cptml/incsys-provider:lates
    ports:
      - "8012:8012"
    environment:
      - INFO_SERVICE_URL=http://infoservice:8000/
    networks:
      - provider
    hostname: incentiveservice
  basketservice:
    image: cptml/incsys-store:latest
    ports:
      - "8010:8010"
    environment:
      - INFO_SERVICE_URL=http://infoservice:8000/
      - INCENTIVE_SERVICE_URL=http://incentiveservice:8012/
    networks:
      - provider
    hostname: basketservice
  bootstrapservice:
    image: cptml/incsys-bootstrap:latest
    environment:
      - BASKET_SERVICE_URLS=http://basketservice:8010/,http://basketservice:8011/
      - INCENTIVE_SERVICE_URL=http://incentiveservice:8012/
    networks:
      - provider
  web:
    image: cptml/incsys-web:latest
    ports:
    - "8080:80"
networks:
  provider:
    driver: bridge
    ipam:
      driver: default
