services:
  infoservice:
    image: cryptimeleon/incentive-service-info:0.5.0
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - PROVIDER_SHARED_SECRET=${SHARED_SECRET}
    networks:
      - provider
    hostname: infoservice
  promotionservice:
    image: cryptimeleon/incentive-service-promotion:0.5.0
    ports:
      - "8012:8012"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - PROVIDER_SHARED_SECRET=${SHARED_SECRET}
      - BASKET_SERVICE_REDEEM_SECRET=${BASKET_REDEEM_SECRET}
      - INCENTIVE_SERVICE_PROVIDER_SECRET=${INCENTIVE_PROVIDER_SECRET}
    networks:
      - provider
    hostname: promotionservice
  basketservice:
    image: cryptimeleon/incentive-service-basket:0.5.0
    ports:
      - "8010:8010"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - BASKET_SERVICE_REDEEM_SECRET=${BASKET_REDEEM_SECRET}
      - BASKET_SERVICE_PAY_SECRET=${BASKET_PAY_SECRET}
      - BASKET_SERVICE_PROVIDER_SECRET=${BASKET_PROVIDER_SECRET}
    networks:
      - provider
    hostname: basketservice
  dsprotectionservice:
    image: cryptimeleon/incentive-service-dsprotection:0.5.0
    ports:
      - "8004:8004"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - provider
    hostname: dsprotectionservice
  bootstrapservice:
    image: cryptimeleon/incentive-service-bootstrap:0.5.0
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - BASKET_SERVICE_PROVIDER_SECRET=${BASKET_PROVIDER_SECRET}
      - INCENTIVE_SERVICE_PROVIDER_SECRET=${INCENTIVE_PROVIDER_SECRET}
    depends_on:
      - basketservice
      - promotionservice
    networks:
      - provider
  web:
    image: cryptimeleon/incentive-system-web:0.5.0
    ports:
      - "8080:80"
networks:
  provider:
    driver: bridge
    ipam:
      driver: default

