version: '3.5'

services:
  infoservice:
    image: cryptimeleon/incentive-service-info:0.5.0
    ports:
      - "8000:8000"
    networks:
      - provider
    hostname: infoservice
  issueservice:
    image: cryptimeleon/incentive-service-issue:0.5.0
    ports:
      - "8001:8001"
    environment:
      - INFO_SERVICE_URL=http://infoservice:8000/
    networks:
      - provider
    hostname: issueservice
  creditservice:
    image: cryptimeleon/incentive-service-credit:0.5.0
    ports:
      - "8002:8002"
    environment:
      - INFO_SERVICE_URL=http://infoservice:8000/
      - BASKET_SERVICE_URL=http://basketservice:8010/
    networks:
      - provider
    hostname: creditservice
  basketservice:
    image: cryptimeleon/incentive-service-basket:0.5.0
    ports:
      - "8010:8010"
    networks:
      - provider
    hostname: basketservice

networks:
  provider:
    driver: bridge
    ipam:
      driver: default

