services:
  infoservice:
    image: cryptimeleon/incentive-service-info:0.5.0
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - PROVIDER_SHARED_SECRET=${PROVIDER_SHARED_SECRET}
      - STORE_SHARED_SECRET=${STORE_SHARED_SECRET}
      - SERVER_SERVLET_CONTEXT_PATH=${INFO_CONTEXT:-/info}
      - SPRINGFOX_HOST=${HOST:-incentives.cs.uni-paderborn.de}
    networks:
      - provider
    hostname: infoservice
  incentiveservice:
    image: cryptimeleon/incentive-service-incentive:0.5.0
    ports:
      - "8012:8012"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - PROVIDER_SHARED_SECRET=${PROVIDER_SHARED_SECRET}
      - BASKET_SERVICE_REDEEM_SECRET=${BASKET_REDEEM_SECRET}
      - INCENTIVE_SERVICE_PROVIDER_SECRET=${INCENTIVE_PROVIDER_SECRET}
      - SERVER_SERVLET_CONTEXT_PATH=${INCENTIVE_CONTEXT:-/incentive}
      - SPRINGFOX_HOST=${HOST:-incentives.cs.uni-paderborn.de}
      - INFO_SERVICE_URL=http://infoservice:8000${INFO_CONTEXT:-/info}
      - BASKET_SERVICE_URL=http://basketservice:8010${BASKET_CONTEXT:-/basket}
      - DSPROTECTION_SERVICE_URL=http://dsprotectionservice:8004${INFO_CONTEXT:-/dsprotection}
    networks:
      - provider
    hostname: incentiveservice
  basketservice:
    image: cryptimeleon/incentive-service-basket:0.5.0
    ports:
      - "8010:8010"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - BASKET_SERVICE_REDEEM_SECRET=${BASKET_REDEEM_SECRET}
      - BASKET_SERVICE_PAY_SECRET=${BASKET_PAY_SECRET}
      - BASKET_SERVICE_PROVIDER_SECRET=${BASKET_PROVIDER_SECRET}
      - STORE_SHARED_SECRET=${STORE_SHARED_SECRET}
      - SERVER_SERVLET_CONTEXT_PATH=${BASKET_CONTEXT:-/basket}
      - SPRINGFOX_HOST=${HOST:-incentives.cs.uni-paderborn.de}
      - INFO_SERVICE_URL=http://infoservice:8000${INFO_CONTEXT:-/info}
    networks:
      - provider
    hostname: basketservice
  bootstrapservice:
    image: cryptimeleon/incentive-service-bootstrap:0.5.0
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - BASKET_SERVICE_PROVIDER_SECRET=${BASKET_PROVIDER_SECRET}
      - INCENTIVE_SERVICE_PROVIDER_SECRET=${INCENTIVE_PROVIDER_SECRET}
      - INCENTIVE_SERVICE_URL=http://incentiveservice:8012${INCENTIVE_CONTEXT:-/incentive}
      - BASKET_SERVICE_URL=http://basketservice:8010${BASKET_CONTEXT:-/basket}
    depends_on:
      - basketservice
      - incentiveservice
    networks:
      - provider
  web:
    image: cryptimeleon/incentive-system-web:0.5.0
    ports:
      - "8080:80"
networks:
  provider:
    driver: bridge
    ipam:
      driver: default

