services:
  issueservice:
    image: cryptimeleon/incentive-service-issue:0.4.0
    ports:
      - "8001:8001"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - PROVIDER_SHARED_SECRET=${SHARED_SECRET}
    networks:
      - provider
    hostname: issueservice
  creditservice:
    image: cryptimeleon/incentive-service-credit:0.4.0
    ports:
      - "8002:8002"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - BASKET_SERVICE_REDEEM_SECRET=${BASKET_REDEEM_SECRET}
      - PROVIDER_SHARED_SECRET=${SHARED_SECRET}
    networks:
      - provider
    hostname: creditservice
  basketservice:
    image: cryptimeleon/incentive-service-basket:0.4.0
    ports:
      - "8003:8003"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - BASKET_SERVICE_REDEEM_SECRET=${BASKET_REDEEM_SECRET}
      - BASKET_SERVICE_PAY_SECRET=${BASKET_PAY_SECRET}
    networks:
      - provider
    hostname: basketservice
  infoservice:
    image: cryptimeleon/incentive-service-info:0.4.0
    ports:
      - "8004:8004"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - PROVIDER_SHARED_SECRET=${SHARED_SECRET}
    networks:
      - provider
    hostname: infoservice
networks:
  provider:
    driver: bridge
    ipam:
      driver: default

