version: '3.5'

services:
  infoservice:
    image: cryptimeleon/incentive-service-info:0.5.0
    ports:
      - "8000:8000"
    networks:
      - provider
    hostname: infoservice
  promotionservice:
    image: cryptimeleon/incentive-service-promotion:0.5.0
    ports:
      - "8012:8012"
    environment:
      - INFO_SERVICE_URL=http://infoservice:8000/
      - BASKET_SERVICE_URL=http://basketservice:8010/
    networks:
      - provider
    hostname: promotionservice
  basketservice:
    image: cryptimeleon/incentive-service-basket:0.5.0
    ports:
      - "8010:8010"
    networks:
      - provider
    hostname: basketservice
  bootstrapservice:
    image: cryptimeleon/incentive-service-bootstrap:0.5.0
    environment:
      - BASKET_SERVICE_URL=http://basketservice:8010/
      - INCENTIVE_SERVICE_URL=http://promotionservice:8012/
    networks:
      - provider
networks:
  provider:
    driver: bridge
    ipam:
      driver: default
