services:
  reverse-proxy:
    image: traefik:v2.9
    command: --providers.docker
    ports:
      - "8009:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - provider
  info:
    image: cptml/incsys-info:latest
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_SERVLET_CONTEXT_PATH=/info
      - PROVIDER_SHARED_SECRET=${PROVIDER_SHARED_SECRET}
      - STORE_SHARED_SECRET=${STORE_SHARED_SECRET}
      - SPRINGFOX_HOST=${HOST:-incentives.cs.uni-paderborn.de}
    labels:
      - traefik.http.routers.info.rule=PathPrefix(`/info`)
      - traefik.http.services.info.loadbalancer.server.port=8000
    networks:
      - provider
    hostname: info
  provider:
    image: cptml/incsys-provider:latest
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_SERVLET_CONTEXT_PATH=/provider
      - PROVIDER_SHARED_SECRET=${PROVIDER_SHARED_SECRET}
      - INCENTIVE_SERVICE_PROVIDER_SECRET=${INCENTIVE_PROVIDER_SECRET}
      - INFO_SERVICE_URL=http://info:8000/info
      - SPRINGFOX_HOST=${HOST:-incentives.cs.uni-paderborn.de}
    labels:
      - traefik.http.routers.provider.rule=PathPrefix(`/provider`)
      - traefik.http.services.provider.loadbalancer.server.port=8012
    networks:
      - provider
    depends_on:
      - info
    hostname: provider
  store:
    image: cptml/incsys-store:latest
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_SERVLET_CONTEXT_PATH=/store
      - STORE_NAME=First Store
      - BASKET_SERVICE_PROVIDER_SECRET=${BASKET_PROVIDER_SECRET}
      - STORE_SHARED_SECRET=${STORE_SHARED_SECRET}
      - INFO_SERVICE_URL=http://info:8000/info
      - INCENTIVE_SERVICE_URL=http://provider:8012/provider
      - SPRINGFOX_HOST=${HOST:-incentives.cs.uni-paderborn.de}
    labels:
      - traefik.http.routers.store.rule=PathPrefix(`/store`)
      - traefik.http.services.store.loadbalancer.server.port=8010
    networks:
      - provider
    depends_on:
      - info
    hostname: store
  store-two:
    image: cptml/incsys-store:latest
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_SERVLET_CONTEXT_PATH=/store-two
      - STORE_NAME=Second Store
      - BASKET_SERVICE_PROVIDER_SECRET=${BASKET_PROVIDER_SECRET_TWO}
      - STORE_SHARED_SECRET=${STORE_SHARED_SECRET}
      - INFO_SERVICE_URL=http://info:8000/info
      - INCENTIVE_SERVICE_URL=http://provider:8012/provider
      - SPRINGFOX_HOST=${HOST:-incentives.cs.uni-paderborn.de}
    labels:
      - traefik.http.routers.store-two.rule=PathPrefix(`/store-two`)
      - traefik.http.services.store-two.loadbalancer.server.port=8010
    networks:
      - provider
    depends_on:
      - info
    hostname: store-two
  bootstrap:
    image: cptml/incsys-bootstrap:latest
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - BASKET_SERVICE_URLS=http://store:8010/store,http://store-two:8010/store-two
      - BASKET_SERVICE_PROVIDER_SECRETS=${BASKET_PROVIDER_SECRET},${BASKET_PROVIDER_SECRET_TWO}
      - INCENTIVE_SERVICE_URL=http://provider:8012/provider
      - INCENTIVE_SERVICE_PROVIDER_SECRET=${INCENTIVE_PROVIDER_SECRET}
    labels:
      - traefik.http.services.store.loadbalancer.server.port=8000
    depends_on:
      - store
      - store-two
      - provider
    networks:
      - provider
  web:
    image: cptml/incsys-web:latest
    ports:
      - "8001:80" # Need 8080 and 80 for traefik
    labels:
      - traefik.http.routers.web.rule=PathPrefix(`/`)
      - traefik.http.services.web.loadbalancer.server.port=80
    networks:
      - provider
networks:
  provider:
    driver: bridge
    ipam:
      driver: default

