services:
  basketservice:
    image: cryptimeleon/incentive-service-basket:0.4.0
    ports:
      - "8003:8003"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - BASKET_SERVICE_REDEEM_SECRET=${BASKET_REDEEM_SECRET}
      - BASKET_SERVICE_PAY_SECRET=${BASKET_PAY_SECRET}
    networks:
      - provider
    hostname: basketservice
  issueservice:
    image: cryptimeleon/incentive-service-issue:0.4.0
    ports:
      - "8001:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_SERVLET_CONTEXT_PATH=/issue
      - INFO_SERVICE_URL=http://infoservice:8000/info/
      - SERVER_PORT=8000
      - PROVIDER_SHARED_SECRET=${SHARED_SECRET}
    networks:
      - provider
    hostname: issueservice
  infoservice:
    image: cryptimeleon/incentive-service-info:0.4.0
    ports:
      - "8004:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_SERVLET_CONTEXT_PATH=/info
      - PROVIDER_SHARED_SECRET=${SHARED_SECRET}
      - SERVER_PORT=8000
    networks:
      - provider
    hostname: infoservice
networks:
  provider:
    driver: bridge
    ipam:
      driver: default

