version: "3"

services:
  basketservice:
    image: cryptimeleon/incentive-service-basket:0.4.0
    ports:
      - "8003:8003"
    hostname: basketservice
  creditservice:
    image: cryptimeleon/incentive-service-credit:0.4.0
    ports:
      - "8002:8002"
    hostname: creditservice
    environment:
      - BASKETSERVICE.URL=http://basketservice:8003
  issueservice:
    image: cryptimeleon/incentive-service-issue:0.4.0
    ports:
      - "8001:8001"
    hostname: issueservice
