package org.cryptimeleon.incentivesystem.dsprotectionservice.mock;

import org.cryptimeleon.incentivesystem.dsprotectionservice.storage.TransactionEntry;
import org.cryptimeleon.incentivesystem.dsprotectionservice.storage.TransactionEntryRepository;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Optional;

public class MockTransactionEntryRepository implements TransactionEntryRepository {
    private HashMap<Long, TransactionEntry> transactionEntries; // stores entries for all transactions in the repo
    private long nextId; // ID to give to the next entry you add to your database

    public MockTransactionEntryRepository() {
        transactionEntries = new HashMap<>();
        nextId = 1;
    }

    /**
     * Stores new entry in DB, returns stored entry.
     */
    public TransactionEntry save(TransactionEntry taEntry) {
        transactionEntries.put(nextId, taEntry);
        // Note: IDs are wrongly autogenerated here
        // (more precisely: always 0)
        // since we do not boot up H2 framework (which would generate incrementing IDs automatically) when using this mock repository
        // => we need to manually set the ID of the new entry to the respective hash map key
        taEntry.setId(nextId);
        nextId++;
        return taEntry;
    }

    /**
     * Stores all transaction entries from a passed list in the DB, returns the said list.
     */
    public <S extends TransactionEntry> Iterable<S> saveAll(Iterable<S> taEntries) {
        for (TransactionEntry tae : taEntries) {
            transactionEntries.put(nextId, tae);
            // Note: IDs are wrongly autogenerated here
            // (more precisely: always 0)
            // since we do not boot up H2 framework (which would generate incrementing IDs automatically) when using this mock repository
            // => we need to manually set the ID of the new entry to the respective hash map key
            tae.setId(nextId);
            nextId++;
        }
        return taEntries;
    }

    /**
     * Returns the entry with the specified id.
     */
    public Optional<TransactionEntry> findById(Long id) {
        return Optional.ofNullable(transactionEntries.get(id));
    }

    /**
     * Returns true if and only if an entry with the passed id exists in the DB.
     */
    public boolean existsById(Long id) {
        return findById(id).isPresent();
    }

    /**
     * Retrieves all entries currently stored in the database.
     *
     * @return ArrayList of transaction entry objects
     */
    public ArrayList<TransactionEntry> findAll() {
        ArrayList<TransactionEntry> results = new ArrayList<>();

        for (Long l : transactionEntries.keySet()) {
            results.add(transactionEntries.get(l));
        }

        return results;
    }

    /**
     * Retrieves the entries with the passed ids.
     *
     * @return ArrayList of transaction entry objects
     */
    public ArrayList<TransactionEntry> findAllById(Iterable<Long> ids) {
        ArrayList<TransactionEntry> results = new ArrayList<>();

        for (long id : ids) {
            Optional<TransactionEntry> tae = findById(id);
            tae.ifPresent(results::add);
        }

        return results;
    }

    /**
     * Returns number of entries that the database currently contains.
     */
    public long count() {
        return transactionEntries.size();
    }

    /**
     * Deletes the entry with the passed id from the database.
     */
    public void deleteById(Long id) {
        transactionEntries.remove(id);
    }

    /**
     * Deletes the passed transaction entry from the database if contained.
     */
    public void delete(TransactionEntry taEntry) {
        for (long l : transactionEntries.keySet()) {
            if (transactionEntries.get(l).equals(taEntry)) {
                transactionEntries.remove(l);
                return;
            }
        }
    }

    /**
     * Deletes all entries from the passed iterable from the database (if an entry is not contained in the database, it is skipped).
     *
     * @param taEntries
     */
    public void deleteAll(Iterable<? extends TransactionEntry> taEntries) {
        for (TransactionEntry tae : taEntries) {
            this.delete(tae);
        }
    }

    /**
     * Clears the database.
     */
    public void deleteAll() {
        this.transactionEntries = new HashMap<>();
    }
}
