package org.cryptimeleon.incentivesystem.cryptoprotocol.interfaces;

public interface SecretKeyMaterialProof {
    // non-interactive ZKP for well-formedness of SPS-EQ secret key and knowing DLog of group elements h_1..h_6 (bases of token excluding h_7)
    String computeSerializedExponentsValidProof(String serializedPublicParameters, String serializedSecretKey);

    // Validate ZKP generated by server
    boolean validateSerializedExponentsProof(String serializedExponentsValidProof, String serializedPublicParameters);
}
