name: Default workflow
on:
  push:
    branches:
      - develop
      - main
      - feature/migrate-pipelines
    tags:
      - v*
  pull_request:
    branches:
      - develop
      - main
  # Daily builds to ensure dependencies don't break anything
  schedule:
    - cron: '00 00 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: |
          pushd incentive-services
          ./gradlew build
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: test-results
          path: /*/reports/test/test/*
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: build
    steps:
      - run: echo "Deploying"
