name: Default workflow
on:
  push:
    branches:
      - develop
      - main
      - feature/pipeline
  pull_request:
    branches:
      - develop
      - main
  # Nightly builds to ensure dependencies don't break anything
  schedule:
    - cron: '00 00 * * *'
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Checkout math
        run: |
          pushd ..
          git clone https://github.com/cryptimeleon/math.git
          pushd math
          git checkout develop
          ./gradlew build
          ./gradlew publishToMavenLocal
      - name: Checkout craco
        run: |
          pushd ..
          git clone https://github.com/cryptimeleon/craco.git
          pushd craco
          git checkout develop
          ./gradlew build
          ./gradlew publishToMavenLocal
      - uses: actions/setup-java@v1
        with:
          java-version: '16' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Checkout incentive-system
        run: |
          pushd ..
          git clone https://github.com/cryptimeleon/incentive-system.git
          pushd incentive-system
          git checkout develop
          ./gradlew cryptoprotocol:build
          ./gradlew cryptoprotocol:publishToMavenLocal
      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - run: ./gradlew build
