name: Default workflow
on:
  push:
  pull_request:
  schedule:
    - cron: '00 00 * * *'

defaults:
  run:
    shell: bash

jobs:
  build-and-integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      - name: Build crypto
        run: |
          pushd crypto
          ./gradlew build
          popd
      - name: Build promotion
        run: |
          pushd promotion
          ./gradlew build
          popd
      - name: Build services
        run: |
          pushd services
          ./gradlew build
          popd
      - name: Run integration tests
        run: |
          ./.github/integration-test.sh kill_services
          ./.github/integration-test.sh start_services
          sleep 15
          ./gradlew :client:integrationTest
          ./.github/integration-test.sh kill_services
          wait

  build-android-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      - name: Build android app
        run: |
          pushd android
          ./gradlew build

  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Build vue project
        run: |
          pushd web
          npm ci
          npm run build
