name: Default workflow
on:
  push:
    branches:
      - develop
      - main
      - feature/migrate-pipelines
  pull_request:
    branches:
      - develop
      - main
  # Daily builds to ensure dependencies don't break anything
  schedule:
    - cron: '00 00 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          path: ./incentive-services
      - name: Checkout math
        uses: actions/checkout@v2
        with:
          repository: upbcuk/upb.crypto.math
          path: ./upb.crypto.math
      - name: Checkout craco
        uses: actions/checkout@v2
        with:
          repository: upbcuk/upb.crypto.craco
          path: ./upb.crypto.craco
      - uses: actions/setup-java@v1
        with:
          java-version: '15.0.1' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - run: |
          pushd incentive-services
          ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: /*/reports/test/test/*
