name: Default workflow
on:
  push:
  pull_request:
  schedule:
    - cron: '00 00 * * *'

defaults:
  run:
    shell: bash

jobs:
  build-and-integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      - name: Build crypto
        run: |
          pushd crypto
          ./gradlew build
          popd
      - name: Build promotion
        run: |
          pushd promotion
          ./gradlew build
          popd
      - name: Build services
        run: |
          pushd services
          ./gradlew build
          popd
      - name: Run integration tests
        run: |
          ./.github/integration-test/start-services.sh
          sleep 30
          pushd services
          ./gradlew :client:integrationTest

  build-android-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      - name: Build android app
        run: |
          pushd android
          ./gradlew build

  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Build vue project
        run: |
          pushd web
          npm ci
          npm run build

  deploy:
    runs-on: ubuntu-latest
    if: true || (github.event_name == 'push' && startsWith(github.ref, 'refs/head/develop'))
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      - name: Deploy
        run: ./.github/docker-release.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN}}
